apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
    app.kubernetes.io/part-of: voting-app
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: local/voting-app-result:1
          resources:
            limits:
              memory: 256M
              cpu: 300m
          ports:
            - containerPort: 80
              name: result-port
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: result-port
      name: result-svc
  selector:
    app: result
